// Regimon GO — 50 evolution families (150 Regimon), generated from compact family data.
// Each family: three stages that grow bigger, fiercer and rarer. Final forms get elite art and a signature move.
(() => {
  const RG = window.RG;
  // [stage names], [types], [habitats], color, belly, glow, [bodies], ears, [extras per stage], accessory, [final rarity], [signature], [descriptions]
  const F = [
    [['Hydrantot', 'Hydrantank', 'Hydrantitan'], ['Water', 'Steel'], ['street'], '#dc2626', '#fecaca', '#38bdf8', ['round', 'wide', 'tall'], 'round', [['antenna'], ['armor', 'bolts'], ['armor', 'crest', 'gradient', 'fangs']], '🚒', 4, ['Hydrant Burst', 'Water', 125, 65, 'stun'],
      ['Sprays kids on hot summer afternoons.', 'Its armored shell can hold back a flood.', 'When it opens its valves, the whole avenue becomes a river.']],
    [['Tokenny', 'Tokenrail', 'Tokenoxus'], ['Steel', 'Electric'], ['subway'], '#ca8a04', '#fef3c7', '#fde047', ['round', 'wide', 'tall'], 'none', [['antenna'], ['bolts', 'armor'], ['bolts', 'crest', 'aura', 'gradient']], '🪙', 4, ['Fare Surge', 'Electric', 125, 65, 'stun'],
      ['An old subway token that rolled away in 2003.', 'It sparks along the third rail looking for turnstiles.', 'Collects every token ever lost under the city.']],
    [['Rooftoad', 'Rooftalon', 'Rooftyrant'], ['Dark', 'Flying'], ['midtown', 'street'], '#374151', '#6b7280', '#f87171', ['wide', 'round', 'tall'], 'tufts', [[], ['bladewings', 'beak'], ['bladewings', 'horns', 'aura', 'fangs']], '', 4, ['Rooftop Dive', 'Flying', 125, 65, 'defDown'],
      ['Sits on water towers and croaks at pigeons.', 'Grew stone wings from perching on old cornices.', 'Rules the skyline after midnight.']],
    [['Bagelbit', 'Bagelbrawl', 'Bagelgeddon'], ['Normal', 'Fire'], ['street', 'nj'], '#c08a4a', '#fde8c8', '#fb923c', ['round', 'wide', 'wide'], 'round', [['spikes'], ['spikes', 'flamecrest'], ['spikes', 'flamecrest', 'aura', 'fangs']], '🥯', 4, ['Everything Explosion', 'Fire', 125, 65, 'burn'],
      ['A fresh bagel that hopped out of the oven.', 'Toasted and ready to fight for the last schmear.', 'Its everything-seed armor burns at 500 degrees.']],
    [['Scaffling', 'Scaffolder', 'Scaffoldraxx'], ['Steel', 'Bug'], ['midtown', 'street'], '#71717a', '#d4d4d8', '#facc15', ['worm', 'wide', 'tall'], 'none', [['antenna'], ['armor', 'claws'], ['armor', 'claws', 'crest', 'aura']], '🚧', 4, ['Sidewalk Shed Slam', 'Steel', 125, 65, 'defDown'],
      ['Crawls up construction poles.', 'Builds sidewalk sheds overnight on every block.', 'Nobody remembers a time before its scaffolding.']],
    [['Neonibble', 'Neonoxious', 'Neonarch'], ['Electric', 'Dark'], ['music', 'midtown'], '#312e81', '#6366f1', '#f0abfc', ['round', 'tall', 'tall'], 'cat', [['bolts'], ['neon', 'bolts', 'tail'], ['neon', 'bolts', 'tail', 'aura', 'crest']], '', 5, ['Marquee Meltdown', 'Electric', 140, 72, 'stun'],
      ['Nibbles on flickering neon letters.', 'Short-circuits every sign on the block.', 'LEGENDARY. Theater marquees spell its name in lights.']],
    [['Leaflet', 'Leafleague', 'Leafleviathan'], ['Grass', 'Water'], ['park', 'water'], '#16a34a', '#bbf7d0', '#4ade80', ['round', 'wide', 'worm'], 'none', [['tailfin'], ['tailfin', 'fin'], ['tailfin', 'fin', 'aura', 'gradient', 'fangs']], '🍃', 4, ['Canopy Tide', 'Grass', 125, 65, 'drain'],
      ['Floats on park ponds like a lily pad.', 'Swims under the Bow Bridge in schools.', 'Its leafy fins cover the whole Lake.']],
    [['Acornet', 'Acornado', 'Acornucopia'], ['Grass', 'Flying'], ['park'], '#92400e', '#fcd34d', '#a3e635', ['round', 'round', 'tall'], 'tufts', [['wings'], ['wings', 'spikes'], ['bladewings', 'crest', 'aura', 'gradient']], '🌰', 4, ['Acorn Cyclone', 'Grass', 125, 65, 'atkUp'],
      ['Squirrels mistake it for lunch.', 'Spins into a tornado of leaves every fall.', 'Every oak in Central Park grew from its seeds.']],
    [['Tidepup', 'Tidehound', 'Tidereaver'], ['Water', 'Dark'], ['river', 'harbor'], '#1e3a8a', '#93c5fd', '#22d3ee', ['round', 'tall', 'tall'], 'floppy', [['tail'], ['tail', 'fin', 'fangs'], ['tail', 'fin', 'fangs', 'aura', 'bladewings']], '', 4, ['Undertow', 'Water', 125, 65, 'defDown'],
      ['Paddles along the esplanade.', 'Chases ferries across the river.', 'The tide turns wherever it howls.']],
    [['Ferrycub', 'Ferrymane', 'Ferryking'], ['Water', 'Royal'], ['harbor', 'nj'], '#0369a1', '#e0f2fe', '#fde047', ['round', 'round', 'tall'], 'round', [['cap'], ['cap', 'mane'], ['mane', 'aura', 'halo', 'gradient']], '⛴️', 4, ['Royal Wake', 'Royal', 125, 65, 'atkUp'],
      ['Rides the Hoboken ferry for free.', 'Its mane flows like a ship\'s wake.', 'Commands every boat in New York Harbor.']],
    [['Roastling', 'Roastrider', 'Roastinferno'], ['Fire', 'Ancient'], ['street', 'park'], '#7c2d12', '#fdba74', '#fb923c', ['round', 'wide', 'wide'], 'round', [['flame'], ['cracks', 'fangs'], ['cracks', 'flamecrest', 'aura', 'fangs']], '🌰', 4, ['Chestnut Inferno', 'Fire', 125, 65, 'burn'],
      ['Smells like roasted nuts from a street cart.', 'Its shell cracks with molten heat.', 'Winters in the city are warm when it is near.']],
    [['Chalkit', 'Chalkodrake', 'Chalkolossus'], ['Brainy', 'Dragon'], ['school'], '#e5e7eb', '#ffffff', '#a5b4fc', ['round', 'tall', 'tall'], 'none', [['glasses'], ['horns', 'tail'], ['horns', 'tail', 'bladewings', 'aura']], '✏️', 4, ['Proof by Fire', 'Dragon', 125, 65, 'atkUp'],
      ['Doodles equations on the sidewalk.', 'Breathes chalk dust across every blackboard.', 'Its proofs are carved into the walls of Regis.']],
    [['Graphling', 'Graphiteon', 'Graphalanx'], ['Brainy', 'Steel'], ['school'], '#475569', '#cbd5e1', '#93c5fd', ['worm', 'tall', 'tall'], 'none', [['antenna'], ['armor', 'glasses'], ['armor', 'crest', 'aura', 'gradient']], '✏️', 4, ['Sharpened Point', 'Steel', 125, 65, 'defDown'],
      ['A pencil stub that learned to wriggle.', 'Takes perfect notes in every class.', 'Leads a phalanx of sharpened pencils into finals week.']],
    [['Hymnote', 'Hymnwing', 'Hymnseraph'], ['Spirit', 'Flying'], ['church', 'music'], '#fef3c7', '#ffffff', '#fbbf24', ['round', 'round', 'tall'], 'none', [['wings'], ['wings', 'halo'], ['bladewings', 'halo', 'aura', 'rays']], '🎶', 4, ['Choir of Light', 'Spirit', 125, 65, 'drain'],
      ['Hums along with the church organ.', 'Its wings ring like bells.', 'Its song fills every cathedral at once.']],
    [['Candlebug', 'Candlemoth', 'Candelabrute'], ['Fire', 'Bug'], ['church'], '#fde68a', '#fffbeb', '#f97316', ['worm', 'round', 'wide'], 'none', [['flame'], ['wings', 'flame'], ['bladewings', 'flamecrest', 'aura']], '🕯️', 4, ['Vigil Flame', 'Fire', 125, 65, 'burn'],
      ['Glows softly in the back pew.', 'Flutters around the altar candles.', 'Carries a hundred flames on its back.']],
    [['Relicub', 'Relicorn', 'Relictaur'], ['Ancient', 'Royal'], ['museum'], '#a16207', '#fde68a', '#fbbf24', ['round', 'tall', 'tall'], 'cat', [[], ['horn', 'armor'], ['horn', 'armor', 'aura', 'crest', 'gradient']], '🏺', 4, ['Ancient Decree', 'Royal', 125, 65, 'atkUp'],
      ['Hides in museum gift shops.', 'Its golden horn was found in a pharaoh\'s tomb.', 'Guards every treasure on Museum Mile.']],
    [['Mosaicat', 'Mosaiclaw', 'Mosaigon'], ['Ancient', 'Dragon'], ['museum', 'church'], '#0e7490', '#a5f3fc', '#22d3ee', ['round', 'wide', 'tall'], 'cat', [['stripes'], ['stripes', 'claws'], ['crystals', 'claws', 'aura', 'bladewings']], '', 4, ['Tessera Storm', 'Ancient', 125, 65, 'defDown'],
      ['Its fur is made of tiny tiles.', 'Rebuilds itself from broken mosaics.', 'A dragon made of ten thousand glittering tiles.']],
    [['Pigmint', 'Pigmentor', 'Pigmentitan'], ['Grass', 'Brainy'], ['museum'], '#65a30d', '#ecfccb', '#f472b6', ['round', 'tall', 'tall'], 'bunny', [[], ['glasses', 'tail'], ['glasses', 'crest', 'aura', 'stars']], '🎨', 4, ['Masterpiece', 'Brainy', 125, 65, 'atkUp'],
      ['Leaves green paw prints on canvas.', 'Teaches painting classes at the Met.', 'Every museum wants its work on the wall.']],
    [['Jazzbit', 'Jazzcat', 'Jazzilla'], ['Electric', 'Normal'], ['music'], '#1e293b', '#f59e0b', '#fbbf24', ['round', 'tall', 'wide'], 'cat', [[], ['tail', 'glasses'], ['tail', 'fangs', 'aura', 'spikes']], '🎷', 4, ['Bebop Blast', 'Electric', 125, 65, 'stun'],
      ['Snaps its fingers on the offbeat.', 'Plays saxophone until 4 a.m.', 'Its solo can shake a whole jazz club.']],
    [['Drumbo', 'Drumblast', 'Drumquake'], ['Athletic', 'Ancient'], ['music', 'sports'], '#b91c1c', '#fecaca', '#f97316', ['round', 'wide', 'wide'], 'round', [[], ['armor'], ['armor', 'spikes', 'aura', 'cracks']], '🥁', 4, ['Seismic Solo', 'Ancient', 125, 65, 'stun'],
      ['Drums on buckets in subway stations.', 'Every beat rattles the platform.', 'Its drum solo registers on earthquake sensors.']],
    [['Hoopling', 'Hoopstar', 'Hooplegend'], ['Athletic', 'Flying'], ['sports'], '#ea580c', '#fed7aa', '#fb923c', ['round', 'tall', 'tall'], 'none', [['headband'], ['headband', 'wings'], ['headband', 'bladewings', 'aura', 'stars']], '🏀', 4, ['Sky Dunk', 'Athletic', 125, 65, 'atkUp'],
      ['Shoots hoops at the playground all day.', 'Never misses from downtown.', 'Its dunks leave cracks in the court.']],
    [['Sluggle', 'Slugger', 'Sluggernaut'], ['Athletic', 'Steel'], ['sports', 'park'], '#1d4ed8', '#dbeafe', '#e5e7eb', ['worm', 'round', 'wide'], 'none', [['cap'], ['cap', 'armor'], ['armor', 'horns', 'aura', 'crest']], '⚾', 4, ['Grand Slam', 'Athletic', 125, 65, 'defDown'],
      ['A slow slug with a big swing.', 'Hits line drives across the Great Lawn.', 'Its home runs land in New Jersey.']],
    [['Puckling', 'Puckbruiser', 'Puckolossus'], ['Ice', 'Athletic'], ['sports'], '#0f172a', '#94a3b8', '#7dd3fc', ['round', 'wide', 'wide'], 'round', [[], ['crystals', 'fangs'], ['crystals', 'armor', 'aura', 'fangs']], '🏒', 4, ['Slap Shot', 'Ice', 125, 65, 'stun'],
      ['Slides around the rink on its belly.', 'Checks opponents into the boards.', 'Its shots freeze the net solid.']],
    [['Flurrby', 'Flurricane', 'Flurrigeddon'], ['Ice', 'Flying'], ['park'], '#e0f2fe', '#ffffff', '#38bdf8', ['round', 'round', 'tall'], 'bunny', [['wings'], ['wings', 'crystals'], ['bladewings', 'crystals', 'aura', 'stars']], '❄️', 5, ['Nor\'easter', 'Ice', 140, 72, 'stun'],
      ['Appears with the first snowflake.', 'Swirls snowdrifts over the park benches.', 'LEGENDARY. Its blizzards shut down the whole city.']],
    [['Slushie', 'Slushark', 'Slushtyrant'], ['Ice', 'Water'], ['river', 'street'], '#7dd3fc', '#e0f2fe', '#a5f3fc', ['round', 'wide', 'tall'], 'none', [['fin'], ['fin', 'tailfin', 'fangs'], ['fin', 'tailfin', 'fangs', 'crystals', 'aura']], '', 4, ['Slush Crush', 'Ice', 125, 65, 'defDown'],
      ['A puddle of gray curbside slush.', 'Soaks anyone who steps off the curb.', 'Freezes the East River in one bite.']],
    [['Dumplit', 'Dimsumo', 'Dimsumperor'], ['Normal', 'Athletic'], ['chinatown'], '#fef3c7', '#ffffff', '#f87171', ['round', 'wide', 'wide'], 'none', [[], ['headband'], ['headband', 'mane', 'aura', 'crest']], '🥟', 4, ['Steamer Slam', 'Athletic', 125, 65, 'atkUp'],
      ['A dumpling that escaped the steamer.', 'Wrestles in Columbus Park at dawn.', 'Rules every dim sum hall on Mott Street.']],
    [['Lanternling', 'Lanternfox', 'Lanternkitsune'], ['Fire', 'Spirit'], ['chinatown'], '#dc2626', '#fde68a', '#fbbf24', ['round', 'tall', 'tall'], 'cat', [['flame'], ['bigtail', 'flame'], ['bigtail', 'flamecrest', 'aura', 'halo', 'stars']], '🏮', 5, ['Nine-Tail Festival', 'Spirit', 140, 72, 'burn'],
      ['Floats above Chinatown streets.', 'Its tail glows like a lantern.', 'LEGENDARY. Lights the Lunar New Year sky.']],
    [['Pitayo', 'Pitayak', 'Pitayadrake'], ['Grass', 'Dragon'], ['chinatown', 'park'], '#db2777', '#fbcfe8', '#a3e635', ['round', 'wide', 'tall'], 'none', [['spikes'], ['spikes', 'tail'], ['spikes', 'horns', 'bladewings', 'aura']], '🐉', 4, ['Dragonfruit Fury', 'Dragon', 125, 65, 'drain'],
      ['A dragonfruit with a sweet temper.', 'Its scales ripen bright pink.', 'Grows a fruit dragon\'s full wingspan.']],
    [['Pennibble', 'Dimewolf', 'Dollardragon'], ['Steel', 'Dragon'], ['finance'], '#b45309', '#fde68a', '#facc15', ['round', 'tall', 'tall'], 'cat', [[], ['fangs', 'tail'], ['fangs', 'tail', 'bladewings', 'aura', 'gradient']], '💰', 4, ['Compound Interest', 'Steel', 125, 65, 'atkUp'],
      ['Picks up pennies on Wall Street.', 'Howls when the market closes.', 'Hoards more gold than the Federal Reserve.']],
    [['Briefcub', 'Briefbeast', 'Briefcaseus'], ['Dark', 'Steel'], ['finance'], '#1f2937', '#6b7280', '#fbbf24', ['round', 'wide', 'tall'], 'round', [[], ['armor'], ['armor', 'mask', 'aura', 'fangs']], '💼', 4, ['Hostile Takeover', 'Dark', 125, 65, 'defDown'],
      ['Carries a tiny briefcase to work.', 'Never takes a lunch break.', 'Buys and sells entire buildings before breakfast.']],
    [['Grotesk', 'Grotesquire', 'Grotesquall'], ['Ghost', 'Ancient'], ['church', 'museum'], '#57534e', '#a8a29e', '#c084fc', ['ghost', 'round', 'tall'], 'tufts', [[], ['bladewings', 'fangs'], ['bladewings', 'horns', 'fangs', 'aura']], '', 5, ['Stone Wail', 'Ghost', 140, 72, 'defDown'],
      ['A little stone face on a church wall.', 'Climbs down from the gutters at night.', 'LEGENDARY. Every gargoyle in the city answers its call.']],
    [['Railrat', 'Railraider', 'Railreaper'], ['Dark', 'Steel'], ['subway'], '#44403c', '#a8a29e', '#ef4444', ['round', 'tall', 'tall'], 'round', [['tail'], ['tail', 'mask', 'fangs'], ['tail', 'mask', 'fangs', 'aura', 'bladewings']], '', 6, ['Last Stop', 'Dark', 150, 78, 'defDown'],
      ['Scurries between the tracks.', 'Rides between subway cars without paying.', 'MYTHIC. Every train that vanishes in the tunnels passes its lair.']],
    [['Gatorlet', 'Sewergator', 'Sewergeddon'], ['Water', 'Dark'], ['subway', 'river'], '#3f6212', '#a3e635', '#84cc16', ['wide', 'wide', 'wide'], 'none', [['snout', 'tail'], ['snout', 'tail', 'teeth', 'armor'], ['snout', 'tail', 'teeth', 'armor', 'aura', 'spikes']], '', 5, ['Sewer Surge', 'Water', 140, 72, 'defDown'],
      ['Someone flushed it as a pet.', 'Grew huge in the tunnels below Manhattan.', 'LEGENDARY. The legend in the sewers was true.']],
    [['Lamplet', 'Lamplighter', 'Lampyros'], ['Electric', 'Fire'], ['street'], '#1f2937', '#fde68a', '#fde047', ['worm', 'tall', 'tall'], 'none', [['antenna'], ['antenna', 'flame'], ['flamecrest', 'bolts', 'aura', 'halo']], '💡', 4, ['Streetlight Flare', 'Electric', 125, 65, 'burn'],
      ['Flickers on at dusk.', 'Lights every lamp on the block.', 'Burns brighter than Times Square.']],
    [['Steamlet', 'Steamrage', 'Steamgeist'], ['Fire', 'Ghost'], ['street', 'midtown'], '#f8fafc', '#ffffff', '#fb923c', ['ghost', 'ghost', 'ghost'], 'none', [[], ['cracks'], ['cracks', 'flamecrest', 'aura']], '', 4, ['Manhole Eruption', 'Fire', 125, 65, 'burn'],
      ['Puffs out of manhole covers.', 'Its orange-striped chimney whistles angrily.', 'The steam pipes under Midtown are its lungs.']],
    [['Skylet', 'Skyspire', 'Skysovereign'], ['Flying', 'Royal'], ['midtown'], '#60a5fa', '#e0f2fe', '#fde68a', ['round', 'tall', 'tall'], 'tufts', [['wings'], ['wings', 'crest'], ['bladewings', 'crest', 'rays', 'aura', 'gradient']], '', 5, ['Top of the World', 'Flying', 140, 72, 'atkUp'],
      ['Rides the wind between skyscrapers.', 'Nests on the tallest antenna it can find.', 'LEGENDARY. Circles the spire of One World Trade.']],
    [['Prismant', 'Prismantis', 'Prismonarch'], ['Bug', 'Ice'], ['midtown'], '#67e8f9', '#ecfeff', '#e879f9', ['round', 'tall', 'tall'], 'none', [['antenna'], ['antenna', 'claws', 'crystals'], ['bladewings', 'claws', 'crystals', 'aura', 'stars']], '', 4, ['Refraction', 'Ice', 125, 65, 'stun'],
      ['Reflects the sun off office windows.', 'Hunts by bending light through glass towers.', 'Its crystal wings throw rainbows over Midtown.']],
    [['Whirlet', 'Whirlpool', 'Whirlwyrm'], ['Water', 'Dragon'], ['river'], '#0891b2', '#a5f3fc', '#67e8f9', ['round', 'worm', 'worm'], 'none', [['spiral'], ['fin', 'tailfin'], ['fin', 'horns', 'aura', 'gradient', 'fangs']], '🌀', 5, ['Hell Gate Vortex', 'Dragon', 140, 72, 'stun'],
      ['A little swirl in the river current.', 'Spins boats in circles near Hell Gate.', 'LEGENDARY. The East River bends around it.']],
    [['Beaconling', 'Beaconeer', 'Beacolossus'], ['Electric', 'Water'], ['harbor'], '#f8fafc', '#fecaca', '#fde047', ['tall', 'tall', 'tall'], 'none', [['flame'], ['flame', 'armor'], ['rays', 'armor', 'aura', 'stars', 'halo']], '🗼', 6, ['Lighthouse Beam', 'Electric', 150, 78, 'stun'],
      ['Blinks on the end of a pier.', 'Guides ferries through the fog.', 'MYTHIC. Its beam reaches every ship on the Atlantic.']],
    [['Spraylet', 'Spraysprite', 'Spraysiren'], ['Water', 'Spirit'], ['harbor', 'river'], '#38bdf8', '#e0f2fe', '#a78bfa', ['round', 'ghost', 'tall'], 'none', [['tailfin'], ['wings', 'halo'], ['bladewings', 'halo', 'aura', 'gills']], '', 4, ['Siren Song', 'Spirit', 125, 65, 'drain'],
      ['Jumps in the spray behind ferries.', 'Sings to sailors on foggy nights.', 'Its song calms the whole harbor.']],
    [['Cliffling', 'Cliffcrusher', 'Cliffcolossus'], ['Ancient', 'Athletic'], ['nj'], '#78716c', '#d6d3d1', '#fb923c', ['round', 'wide', 'wide'], 'none', [[], ['armor', 'cracks'], ['armor', 'cracks', 'spikes', 'aura']], '🪨', 5, ['Palisade Avalanche', 'Ancient', 140, 72, 'defDown'],
      ['A pebble from the Palisades.', 'Punches holes in the cliffs of Weehawken.', 'LEGENDARY. It IS the Palisades.']],
    [['Sizzlet', 'Sizzleclaw', 'Sizzlesaur'], ['Fire', 'Normal'], ['nj', 'street'], '#ea580c', '#fed7aa', '#f97316', ['round', 'wide', 'tall'], 'none', [['flame'], ['claws', 'flame'], ['claws', 'flamecrest', 'crest', 'aura', 'fangs']], '🍳', 4, ['Diner Griddle', 'Fire', 125, 65, 'burn'],
      ['Sizzles on a Jersey diner griddle.', 'Flips pancakes with its claws.', 'Open 24 hours, and always on fire.']],
    [['Tunnelmole', 'Tunnelmaw', 'Tunnelmonarch'], ['Ancient', 'Steel'], ['subway', 'nj'], '#57534e', '#d6d3d1', '#fbbf24', ['round', 'wide', 'wide'], 'round', [['claws'], ['claws', 'armor'], ['claws', 'armor', 'crest', 'aura']], '⛏️', 4, ['Deep Bore', 'Ancient', 125, 65, 'defDown'],
      ['Digs little holes under the PATH.', 'Carved the tunnels under the Hudson.', 'Rules every tunnel from Manhattan to Newark.']],
    [['Pierling', 'Pierprowler', 'Pierpredator'], ['Water', 'Normal'], ['nj', 'river'], '#1e40af', '#bfdbfe', '#60a5fa', ['round', 'tall', 'wide'], 'cat', [['tail'], ['tail', 'fangs'], ['tail', 'fangs', 'fin', 'aura', 'mask']], '', 4, ['Pier Pounce', 'Water', 125, 65, 'atkUp'],
      ['Fishes off the Hoboken piers.', 'Stalks the waterfront at night.', 'Nothing crosses its pier uninvited.']],
    [['Trotlet', 'Trotstallion', 'Trotcentaur'], ['Normal', 'Royal'], ['park'], '#e7e5e4', '#ffffff', '#fde68a', ['round', 'tall', 'tall'], 'floppy', [['tail'], ['mane', 'tail'], ['mane', 'tail', 'horn', 'aura', 'halo']], '🐎', 4, ['Carriage Charge', 'Royal', 125, 65, 'atkUp'],
      ['Clip-clops down the park drive.', 'Pulls carriages past the Plaza Hotel.', 'Its gallop echoes across all of Central Park.']],
    [['Shellby', 'Shellbrute', 'Shelltitan'], ['Water', 'Ancient'], ['water', 'park'], '#4d7c0f', '#d9f99d', '#a3e635', ['wide', 'wide', 'wide'], 'none', [['shell'], ['shell', 'spikes'], ['shell', 'spikes', 'crystals', 'aura']], '🐢', 4, ['Shell Quake', 'Ancient', 125, 65, 'defDown'],
      ['Suns itself on a Turtle Pond rock.', 'Its shell grew spikes over 100 years.', 'Carries a whole island on its back.']],
    [['Heronette', 'Heronblade', 'Heronimbus'], ['Flying', 'Water'], ['water', 'park'], '#94a3b8', '#f1f5f9', '#bae6fd', ['tall', 'tall', 'tall'], 'tufts', [['beak'], ['beak', 'bladewings'], ['beak', 'bladewings', 'halo', 'aura']], '', 4, ['Cloud Spear', 'Flying', 125, 65, 'defDown'],
      ['Stands perfectly still in the Harlem Meer.', 'Its wings are sharp as knives.', 'Walks on clouds above the Reservoir.']],
    [['Rambat', 'Ramblade', 'Rambletyr'], ['Dark', 'Grass'], ['park'], '#14532d', '#4ade80', '#a3e635', ['round', 'round', 'tall'], 'cat', [['wings'], ['bladewings'], ['bladewings', 'fangs', 'aura', 'horns']], '', 4, ['Ramble Ambush', 'Dark', 125, 65, 'drain'],
      ['Sleeps in the trees of the Ramble.', 'Gets lost on purpose on the winding paths.', 'The Ramble grows darker when it hunts.']],
    [['Hawklet', 'Hawkavenue', 'Hawkemperor'], ['Flying', 'Royal'], ['park', 'street'], '#9a3412', '#fed7aa', '#fbbf24', ['round', 'tall', 'tall'], 'tufts', [['wings', 'beak'], ['bladewings', 'beak'], ['bladewings', 'beak', 'crest', 'aura', 'rays']], '', 5, ['Fifth Avenue Strike', 'Flying', 140, 72, 'atkUp'],
      ['Hatched on a Fifth Avenue ledge.', 'Hunts pigeons over the Park.', 'LEGENDARY. The most famous hawk in New York.']],
    [['Phantomime', 'Phantomask', 'Phantomaestro'], ['Ghost', 'Brainy'], ['music'], '#f5f5f4', '#ffffff', '#c084fc', ['ghost', 'ghost', 'ghost'], 'none', [[], ['mask'], ['mask', 'aura', 'halo', 'stars']], '🎭', 6, ['Final Curtain', 'Ghost', 150, 78, 'stun'],
      ['Mimes silently in Washington Square.', 'Haunts the balcony of an old theater.', 'MYTHIC. Conducts an orchestra of ghosts every midnight.']],
  ];
  let id = 104;
  for (const f of F) {
    const [names, types, habitat, color, belly, glow, bodies, ears, extras, acc, finalR, sig, descs] = f;
    const startR = ['Hydrantot', 'Bagelbit', 'Railrat', 'Leaflet', 'Tidepup', 'Acornet'].includes(names[0]) ? 1 : 2;
    const rarities = [startR, 3, finalR];
    const famId = id;
    names.forEach((name, s) => {
      RG.SPECIES.push({
        id: id++, name, types: s === 0 && types.length > 1 ? [types[0]] : types, rarity: rarities[s], habitat,
        body: bodies[s], color, belly, ears,
        eyes: s === 0 ? undefined : 'fierce', glow, extras: extras[s], acc: s === 2 ? '' : acc, accPos: 'hand',
        sig: s === 2 ? sig : undefined, family: famId, stage: s + 1, desc: descs[s],
      });
    });
  }
})();
